In [25]:
from influxdb import InfluxDBClient
from datetime import datetime
import time

In [11]:
# Setup database
client = InfluxDBClient('localhost', 8086, 'MPODs')
client.create_database('MPODs')
client.switch_database('MPODs')
client.get_list_database()

[{'name': '_internal'},
 {'name': 'argoncube'},
 {'name': 'gizmo'},
 {'name': 'MPODs'}]

In [29]:
# Setup payload
json_payload = []
data = {
    # Table name
    "measurement" : "light", 
    # Organizing data stuff
    "tags" : { 
        "module" : "VGA_12_pos",
        "status" : "OFF"
    },
    # Time stamp
    "time" : datetime.now(), 
    # Data fields
    "fields" : { 
        "voltage" : 0.5,
        "current" : 0.25
    }
}
json_payload.append(data)

def JSON_setup(measurement, module, status, voltage, current):
    return {
        # Table name
        "measurement" : measurement, 
        # Organizing data stuff
        "tags" : { 
            "module" : module,
            "status" : status
        },
        # Time stamp
        "time" : datetime.now(), 
        # Data fields
        "fields" : { 
            "voltage" : voltage,
            "current" : current
        }
    }
json_payload.append(data)
#time.sleep(5)

In [33]:
data = JSON_setup("Light", "VGA_12_pos", "OFF", 0.75, 0.85)
json_payload.append(data)

In [32]:
# Send our payload
client.write_points(json_payload)

True

In [23]:
result = client.query('select * from light')
result

ResultSet({'('light', None)': [{'time': '2023-07-18T14:29:32.381906Z', 'current': 0.25, 'module': 'VGA_12_pos', 'status': 'OFF', 'voltage': 0.5}]})

In [60]:
import numpy as np
matrix = np.array([[0,0,0],[2,3,1],[2,2,2],[2,2,2]])
matrix

array([[0, 0, 0],
       [2, 3, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [43]:
def my_function(column):

    return result

In [49]:
result = np.apply_along_axis(axis=0, arr=matrix)
result

TypeError: _apply_along_axis_dispatcher() missing 1 required positional argument: 'func1d'

In [54]:
def INFLUX_write(self, powering, modules, data, mpod):
    for module_number in len(data):
        data_column = data[:,module_number]
        measurement = powering
        module = modules[module_number]
        status = data_column[0]
        voltage = data_column[1]
        current = data_column[2]
        client.write_points(mpod.JSON_setup(
            measurement = powering,
            module = modules[module_number],
            status = data_column[0],
            voltage = data_column[1],
            current = data_column[2]
		))

In [58]:
for module_number in range(0,len(matrix)):
    print(module_number)
    data_column = matrix[:,module_number]
    print(data_column)

0
[0 2 2]
1
[0 3 2]
2
[0 1 2]


In [61]:
len(matrix)

4

In [67]:
datetime.now().strftime('%Y%m%d %H:%M:%S')

'20230718 17:21:53'

In [71]:
my_dict = {
    'apple': 1,
    'banana': 2,
    'cherry': 3
}

first_letters = [key[0] for key in my_dict]
print(first_letters)


['a', 'b', 'c']


In [80]:
list(my_dict.items())[1][1]

2

In [85]:
print("What would you like to control? \n - Charge \n - Light \n - Rtd \n - All")


SyntaxError: EOL while scanning string literal (<ipython-input-85-ed2c9a5de4ee>, line 1)